import { NutritionModel } from '../shared/models/nutrition.model';

export const nutritionFacts: NutritionModel[] = [
  {
    name: 'Raw Peanuts (1g)',
    quantity: 1,
    totalCalories: 0.6,
    totalKj: 3,
    nutritionFacts: {
      totalFat: 0.1,
      totalFatPercentage: 0.1,
      saturatedFat: 0.08,
      polyunsaturatedFat: 0.01,
      monounsaturatedFat: 0.01,
      cholesterol: 0.03,
      totalCholesterolPercentage: 0.03,
      sodium: 1.2,
      totalSodiumPercentage: 0.01,
      totalCarbohydrate: 0.5,
      totalCarbohydratePercentage: 0.01,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0.5,
      protein: 0.3,
      calcium: 1.6,
      potassium: 1.5,
      iron: 0.03,
      vitA: 1,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Whole Milk 3.5% fat (1ml)',
    quantity: 1,
    totalCalories: 9,
    totalKj: 3,
    nutritionFacts: {
      totalFat: 0.5,
      totalFatPercentage: 0.8,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.1,
      monounsaturatedFat: 0.1,
      cholesterol: 2,
      totalCholesterolPercentage: 0.5,
      sodium: 6,
      totalSodiumPercentage: 0.3,
      totalCarbohydrate: 0.8,
      totalCarbohydratePercentage: 0.3,
      fiber: 0.1,
      totalFiberPercentage: 0,
      sugars: 0.8,
      protein: 0.5,
      calcium: 17,
      potassium: 22,
      iron: 1,
      vitA: 15,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'White Bread (slice)',
    quantity: 1,
    totalCalories: 79,
    totalKj: 332,
    nutritionFacts: {
      totalFat: 1,
      totalFatPercentage: 1,
      saturatedFat: 0.2,
      polyunsaturatedFat: 1,
      monounsaturatedFat: 0.2,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 147,
      totalSodiumPercentage: 6,
      totalCarbohydrate: 14.7,
      totalCarbohydratePercentage: 5,
      fiber: 0.8,
      totalFiberPercentage: 3,
      sugars: 1.5,
      protein: 2.7,
      calcium: 78,
      potassium: 35,
      iron: 1,
      vitA: 15,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Avocados (fruit)',
    quantity: 1,
    totalCalories: 321,
    totalKj: 1344,
    nutritionFacts: {
      totalFat: 29.5,
      totalFatPercentage: 45,
      saturatedFat: 4.3,
      polyunsaturatedFat: 3.7,
      monounsaturatedFat: 19.7,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 14,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 17.1,
      totalCarbohydratePercentage: 6,
      fiber: 13.5,
      totalFiberPercentage: 54,
      sugars: 1.3,
      protein: 4,
      calcium: 24,
      potassium: 975,
      iron: 1,
      vitA: 291,
      vitC: 20,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Tomatoes (whole 2,5")',
    quantity: 1,
    totalCalories: 22,
    totalKj: 93,
    nutritionFacts: {
      totalFat: 0.2,
      totalFatPercentage: 0,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 6,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 4.8,
      totalCarbohydratePercentage: 2,
      fiber: 1.5,
      totalFiberPercentage: 6,
      sugars: 3.2,
      protein: 1.1,
      calcium: 12,
      potassium: 292,
      iron: 1,
      vitA: 1027,
      vitC: 16,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Brown Rice (100g)',
    quantity: 1,
    totalCalories: 111,
    totalKj: 464,
    nutritionFacts: {
      totalFat: 0.9,
      totalFatPercentage: 1,
      saturatedFat: 0.2,
      polyunsaturatedFat: 0.3,
      monounsaturatedFat: 0.3,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 5,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 23,
      totalCarbohydratePercentage: 8,
      fiber: 1.8,
      totalFiberPercentage: 7,
      sugars: 0.4,
      protein: 2.6,
      calcium: 10,
      potassium: 43,
      iron: 1,
      vitA: 1027,
      vitC: 16,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Whole Wheat Pasta (100g)',
    quantity: 1,
    totalCalories: 111,
    totalKj: 464,
    nutritionFacts: {
      totalFat: 0.9,
      totalFatPercentage: 1,
      saturatedFat: 0.2,
      polyunsaturatedFat: 0.3,
      monounsaturatedFat: 0.3,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 5,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 23,
      totalCarbohydratePercentage: 8,
      fiber: 1.8,
      totalFiberPercentage: 7,
      sugars: 0.4,
      protein: 2.6,
      calcium: 10,
      potassium: 43,
      iron: 1,
      vitA: 1027,
      vitC: 16,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Potato French Fries (100g)',
    quantity: 1,
    totalCalories: 314,
    totalKj: 1313,
    nutritionFacts: {
      totalFat: 16.1,
      totalFatPercentage: 25,
      saturatedFat: 2.1,
      polyunsaturatedFat: 4.7,
      monounsaturatedFat: 7.8,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 290,
      totalSodiumPercentage: 12,
      totalCarbohydrate: 38.4,
      totalCarbohydratePercentage: 13,
      fiber: 3.5,
      totalFiberPercentage: 14,
      sugars: 0.7,
      protein: 3.8,
      calcium: 13,
      potassium: 550,
      iron: 1,
      vitA: 0,
      vitC: 3,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Potatoes (100g)',
    quantity: 1,
    totalCalories: 86,
    totalKj: 359,
    nutritionFacts: {
      totalFat: 0.1,
      totalFatPercentage: 0.1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.1,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 5,
      totalSodiumPercentage: 0.1,
      totalCarbohydrate: 20,
      totalCarbohydratePercentage: 7,
      fiber: 1.8,
      totalFiberPercentage: 7,
      sugars: 0.9,
      protein: 1.7,
      calcium: 8,
      potassium: 328,
      iron: 1,
      vitA: 5,
      vitC: 7,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Spinach (100g)',
    quantity: 1,
    totalCalories: 23,
    totalKj: 96,
    nutritionFacts: {
      totalFat: 0.4,
      totalFatPercentage: 1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.2,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 79,
      totalSodiumPercentage: 3,
      totalCarbohydrate: 3.6,
      totalCarbohydratePercentage: 1,
      fiber: 2.2,
      totalFiberPercentage: 9,
      sugars: 0.4,
      protein: 2.9,
      calcium: 99,
      potassium: 558,
      iron: 3,
      vitA: 9375,
      vitC: 28,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Broccoli (100g)',
    quantity: 1,
    totalCalories: 34,
    totalKj: 142,
    nutritionFacts: {
      totalFat: 0.4,
      totalFatPercentage: 1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.1,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 33,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 6.6,
      totalCarbohydratePercentage: 2,
      fiber: 2.6,
      totalFiberPercentage: 10,
      sugars: 1.7,
      protein: 2.8,
      calcium: 47,
      potassium: 316,
      iron: 1,
      vitA: 625,
      vitC: 89,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Milk Chocolate (100g)',
    quantity: 1,
    totalCalories: 534,
    totalKj: 2236,
    nutritionFacts: {
      totalFat: 35,
      totalFatPercentage: 55,
      saturatedFat: 14.2,
      polyunsaturatedFat: 0.9,
      monounsaturatedFat: 13.2,
      cholesterol: 23,
      totalCholesterolPercentage: 8,
      sodium: 79,
      totalSodiumPercentage: 3,
      totalCarbohydrate: 59.4,
      totalCarbohydratePercentage: 20,
      fiber: 3.4,
      totalFiberPercentage: 14,
      sugars: 51.5,
      protein: 7.7,
      calcium: 189,
      potassium: 372,
      iron: 2,
      vitA: 175,
      vitC: 0,
      caffeine: 20,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: 'Chicken Breast (100g)',
    quantity: 1,
    totalCalories: 110,
    totalKj: 460,
    nutritionFacts: {
      totalFat: 1.2,
      totalFatPercentage: 2,
      saturatedFat: 0.3,
      polyunsaturatedFat: 0.3,
      monounsaturatedFat: 0.3,
      cholesterol: 58,
      totalCholesterolPercentage: 19,
      sodium: 65,
      totalSodiumPercentage: 3,
      totalCarbohydrate: 0,
      totalCarbohydratePercentage: 0,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0,
      protein: 23.1,
      calcium: 11,
      potassium: 255,
      iron: 1,
      vitA: 20,
      vitC: 1,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Apple (medium 3")',
    quantity: 1,
    totalCalories: 93,
    totalKj: 389,
    nutritionFacts: {
      totalFat: 0.3,
      totalFatPercentage: 0.1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.1,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 2,
      totalSodiumPercentage: 0.1,
      totalCarbohydrate: 24.7,
      totalCarbohydratePercentage: 8,
      fiber: 4.3,
      totalFiberPercentage: 17,
      sugars: 18.6,
      protein: 0.5,
      calcium: 11,
      potassium: 192,
      iron: 1,
      vitA: 98,
      vitC: 8,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Red Sweet Pepper (whole 3,5")',
    quantity: 1,
    totalCalories: 42,
    totalKj: 177,
    nutritionFacts: {
      totalFat: 0.5,
      totalFatPercentage: 1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.3,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 3,
      totalSodiumPercentage: 0.1,
      totalCarbohydrate: 10.3,
      totalCarbohydratePercentage: 3,
      fiber: 3.4,
      totalFiberPercentage: 14,
      sugars: 6.8,
      protein: 1.6,
      calcium: 11,
      potassium: 344,
      iron: 1,
      vitA: 5102,
      vitC: 310,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Old Country Style Muesli (100g)',
    quantity: 1,
    totalCalories: 400,
    totalKj: 1674,
    nutritionFacts: {
      totalFat: 8.6,
      totalFatPercentage: 13,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 0,
      totalSodiumPercentage: 0,
      totalCarbohydrate: 65.7,
      totalCarbohydratePercentage: 22,
      fiber: 11.4,
      totalFiberPercentage: 46,
      sugars: 14.3,
      protein: 11.4,
      calcium: 57,
      potassium: 486,
      iron: 3,
      vitA: 0,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Ground Beef (100g)',
    quantity: 1,
    totalCalories: 152,
    totalKj: 636,
    nutritionFacts: {
      totalFat: 7,
      totalFatPercentage: 11,
      saturatedFat: 2.9,
      polyunsaturatedFat: 0.3,
      monounsaturatedFat: 2.9,
      cholesterol: 65,
      totalCholesterolPercentage: 22,
      sodium: 66,
      totalSodiumPercentage: 3,
      totalCarbohydrate: 0,
      totalCarbohydratePercentage: 0,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0,
      protein: 20.9,
      calcium: 10,
      potassium: 336,
      iron: 2,
      vitA: 14,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Salted Plain Potato Chips (100g)',
    quantity: 1,
    totalCalories: 546,
    totalKj: 2286,
    nutritionFacts: {
      totalFat: 37.5,
      totalFatPercentage: 58,
      saturatedFat: 11,
      polyunsaturatedFat: 12.2,
      monounsaturatedFat: 9.8,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 525,
      totalSodiumPercentage: 22,
      totalCarbohydrate: 49.7,
      totalCarbohydratePercentage: 17,
      fiber: 4.4,
      totalFiberPercentage: 18,
      sugars: 4.1,
      protein: 6.6,
      calcium: 24,
      potassium: 1642,
      iron: 2,
      vitA: 0,
      vitC: 19,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Yogurt O % (100g)',
    quantity: 1,
    totalCalories: 57,
    totalKj: 240,
    nutritionFacts: {
      totalFat: 0,
      totalFatPercentage: 0,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 4,
      totalCholesterolPercentage: 1,
      sodium: 33,
      totalSodiumPercentage: 1,
      totalCarbohydrate: 3.1,
      totalCarbohydratePercentage: 1,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 3.1,
      protein: 10.6,
      calcium: 110,
      potassium: 0,
      iron: 0,
      vitA: 0,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Beer Heineken 5 % alc. (500ml)',
    quantity: 1,
    totalCalories: 148,
    totalKj: 618,
    nutritionFacts: {
      totalFat: 0,
      totalFatPercentage: 0,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 7,
      totalSodiumPercentage: 0.01,
      totalCarbohydrate: 11.3,
      totalCarbohydratePercentage: 4,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0,
      protein: 1.5,
      calcium: 0,
      potassium: 0,
      iron: 0,
      vitA: 0,
      vitC: 0,
      alcohol: 13.8,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Pearled Barley (100g)',
    quantity: 1,
    totalCalories: 123,
    totalKj: 514,
    nutritionFacts: {
      totalFat: 0.4,
      totalFatPercentage: 1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.2,
      monounsaturatedFat: 0.1,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 3,
      totalSodiumPercentage: 0.001,
      totalCarbohydrate: 28.2,
      totalCarbohydratePercentage: 9,
      fiber: 3.8,
      totalFiberPercentage: 15,
      sugars: 0.3,
      protein: 2.3,
      calcium: 11,
      potassium: 93,
      iron: 1,
      vitA: 5,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Buckwheat Groats (100g)',
    quantity: 1,
    totalCalories: 92,
    totalKj: 385,
    nutritionFacts: {
      totalFat: 0.6,
      totalFatPercentage: 1,
      saturatedFat: 0.1,
      polyunsaturatedFat: 0.2,
      monounsaturatedFat: 0.2,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 4,
      totalSodiumPercentage: 0.001,
      totalCarbohydrate: 19.9,
      totalCarbohydratePercentage: 7,
      fiber: 2.7,
      totalFiberPercentage: 11,
      sugars: 0.9,
      protein: 3.4,
      calcium: 7,
      potassium: 88,
      iron: 1,
      vitA: 0,
      vitC: 0,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Vodka 40 % alc. (shot 50 ml)',
    quantity: 1,
    totalCalories: 109,
    totalKj: 456,
    nutritionFacts: {
      totalFat: 0,
      totalFatPercentage: 0,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 0,
      totalSodiumPercentage: 0,
      totalCarbohydrate: 0.1,
      totalCarbohydratePercentage: 0.001,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0,
      protein: 0,
      calcium: 0,
      potassium: 0,
      iron: 0,
      vitA: 0,
      vitC: 0,
      alcohol: 15.8,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
  {
    name: ' Pinot Noir Red Wine 10 % alc. (glass 150 ml)',
    quantity: 1,
    totalCalories: 124,
    totalKj: 520,
    nutritionFacts: {
      totalFat: 0,
      totalFatPercentage: 0,
      saturatedFat: 0,
      polyunsaturatedFat: 0,
      monounsaturatedFat: 0,
      cholesterol: 0,
      totalCholesterolPercentage: 0,
      sodium: 0,
      totalSodiumPercentage: 0,
      totalCarbohydrate: 3.5,
      totalCarbohydratePercentage: 1,
      fiber: 0,
      totalFiberPercentage: 0,
      sugars: 0,
      protein: 0.1,
      calcium: 0,
      potassium: 0,
      iron: 0,
      vitA: 0,
      vitC: 0,
      alcohol: 15.6,
    },
    timeToBurn: {
      swimming: 1,
      running: 1.5,
      cycling: 2,
      walking: 4,
    }
  },
];
